### ISSUE TITLE
easy_install deprecated - issue in single-node ubuntu 16.04 install

### ISSUE THREAD

**Issue by charles-sol-analytica** [aws-quickstart/quickstart-tableau-server#90] opened 2021-05-11 05:12 UTC
Issue: CF build fails on timeout because CF isn't notified of completion by the cfn-signal.  cfn function aren't properly installed 

I've modified my template from before this issue - so it's possible this isn't an issue in main. But with the deprecation of easy_install, my server wouldn't build. I replaced the easy_install line with the following code and updated the path to cfn functions as a workaround:

```
#this from https://aws.amazon.com/blogs/infrastructure-and-automation/introduction-to-quickstart-linux-utilities/ as an alternative to easy_install which is apparently deprecated
            until git clone https://github.com/aws-quickstart/quickstart-linux-utilities.git; do echo "Retrying"; done
            cd /quickstart-linux-utilities
            source quickstart-cfn-tools.source
            qs_update-os || qs_err
            qs_bootstrap_pip || qs_err
            qs_aws-cfn-bootstrap || qs_err

#now cfn functions at here: /usr/local/bin/cfn-init 
#remove easy_install reference 
#/usr/bin/easy_install --script-dir /opt/aws/bin https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz 
            #/opt/aws/bin/cfn-init --stack ${AWS::StackName} --resource TableauServer --region ${AWS::Region}
            
#replace cfn-init references (though this may not be necessary because it's on the path

            /usr/local/bin/cfn-init --stack ${AWS::StackName} --resource TableauServer --region ${AWS::Region}
            # Various machine configs
            hostnamectl set-hostname $(hostnamectl --static)
            echo "before call sftp" >> /tmp/logging.txt
            setup_sftp() {
                source '/tmp/secrets.properties'
                useradd -m "$tsm_admin_user"
                echo -e "$tsm_admin_pass\n$tsm_admin_pass" | passwd "$tsm_admin_user"

            }
```

**Comment by odubyk** [comment] 2021-05-19 20:18
the same issue, fixed by installing pip and `pip install aws-cfn-bootstrap`

**Comment by kornelbicskei** [comment] 2021-05-21 20:37
This should get fixed soon by our revamp of the QuickStarts, initial PR is out for dev branch, ubuntu template: 
https://github.com/aws-quickstart/quickstart-tableau-server/pull/89

**Comment by aflansburg** [comment] 2022-03-03 22:22
Can confirm this is still an issue when using this template to provision an Ubuntu Tableau Server instance.
A look at the logs in `/var/log/cloud-*.log` show some missing python dependencies may be the cause of the cfn-signal failing to emit:

```
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-signal", line 4, in <module>
    __import__('pkg_resources').run_script('aws-cfn-bootstrap==1.4', 'cfn-signal')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pystache<0.6.0,>=0.4.0' distribution was not found and is required by aws-cfn-bootstrap
```

I will see if I can update my template and at least report back with a workaround ¯\_(ツ)_/¯ Tableau should probably remove this quickstart option from their site until it's fixed......

**Comment by aflansburg** [comment] 2022-03-04 15:23
> I will see if I can update my template and at least report back with a workaround ¯_(ツ)_/¯ Tableau should probably remove this quickstart option from their site until it's fixed......

I ended up just editing the main template and the WorkloadStack template, commented out the easy_install bit, and (using python2.7/pip for whatever reason will work with current pystache dependency ver requirement without installing older version using python3/pip3) - updated the WorkloadStack section:
```
 #!/bin/bash -x

            apt-get update

            apt-get install -y python-setuptools
            
            # added pip2
            apt-get install --yes python-pip
            # installed aws-cfn-boostrap with pip2
            /usr/bin/pip install aws-cfn-bootstrap

            # Call Init

            # /usr/bin/easy_install --script-dir /opt/aws/bin
            # https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz

            # updated location of cfn to /usr/local/bin
            /usr/local/bin/cfn-init --stack ${AWS::StackName} --resource
            TableauServer --region ${AWS::Region}

            ...
            # further down updated location again for cfn-signal
            # Signal successful completion

            /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource
            TableauServer --region ${AWS::Region}
```

**Comment by MoeniebDavidsAltron** [comment] 2022-09-14 09:19
@aflansburg 
Is your fix still relevant?
I seem to also have the same issue with the quick start install and it fails on EC2

**Comment by vsnyc** [comment] 2022-09-22 18:57
This is no longer relevant, the Quick Start has been updated and only supports Amazon Linux 2 and Windows Server 2019

**Closed by vsnyc** 2022-09-22 18:57 UTC

**Comment by MoeniebDavidsAltron** [comment] 2022-09-23 05:48
Hi @vsnyc ,

Based on the selections on the template, I have selected the "Linux" option, and still get the issue.
So, is this then the wrong version of Linux or should there be an option for Amazon Linux 2?
Apologies if the question sounds amateur, but I am not sure if Amazon Linux 2 is referred to by the Linux option in the template
